spring:
  application:
    name: consumer-service-feign
server:
  port: 9001
eureka:
  instance:
    hostname: cloud-consumer-feign-service
  client:
    service-url:
      defaultZone: http://cloud-eureka-service:7000/eureka/
