spring:
  application:
    name: provider-service
server:
  port: 8000
eureka:
  instance:
    hostname: cloud-provider-service
  client:
    service-url:
      defaultZone: http://cloud-eureka-service:7000/eureka/
